// Autogenerated from Pigeon (v22.4.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum PermisionsApi: Int {
  case granted = 0
  case denied = 1
  case restricted = 2
  case unknown = 3
  case notDetermined = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct Name {
  var first: String
  var last: String
  var middle: String
  var prefix: String
  var suffix: String
  var nickname: String
  var firstPhonetic: String
  var lastPhonetic: String
  var middlePhonetic: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Name? {
    let first = pigeonVar_list[0] as! String
    let last = pigeonVar_list[1] as! String
    let middle = pigeonVar_list[2] as! String
    let prefix = pigeonVar_list[3] as! String
    let suffix = pigeonVar_list[4] as! String
    let nickname = pigeonVar_list[5] as! String
    let firstPhonetic = pigeonVar_list[6] as! String
    let lastPhonetic = pigeonVar_list[7] as! String
    let middlePhonetic = pigeonVar_list[8] as! String

    return Name(
      first: first,
      last: last,
      middle: middle,
      prefix: prefix,
      suffix: suffix,
      nickname: nickname,
      firstPhonetic: firstPhonetic,
      lastPhonetic: lastPhonetic,
      middlePhonetic: middlePhonetic
    )
  }
  func toList() -> [Any?] {
    return [
      first,
      last,
      middle,
      prefix,
      suffix,
      nickname,
      firstPhonetic,
      lastPhonetic,
      middlePhonetic,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Phone {
  var number: String
  var normalizedNumber: String
  var label: String
  var customLabel: String
  var isPrimary: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Phone? {
    let number = pigeonVar_list[0] as! String
    let normalizedNumber = pigeonVar_list[1] as! String
    let label = pigeonVar_list[2] as! String
    let customLabel = pigeonVar_list[3] as! String
    let isPrimary = pigeonVar_list[4] as! Bool

    return Phone(
      number: number,
      normalizedNumber: normalizedNumber,
      label: label,
      customLabel: customLabel,
      isPrimary: isPrimary
    )
  }
  func toList() -> [Any?] {
    return [
      number,
      normalizedNumber,
      label,
      customLabel,
      isPrimary,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Email {
  var address: String
  var label: String
  var customLabel: String
  var isPrimary: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Email? {
    let address = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let customLabel = pigeonVar_list[2] as! String
    let isPrimary = pigeonVar_list[3] as! Bool

    return Email(
      address: address,
      label: label,
      customLabel: customLabel,
      isPrimary: isPrimary
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      label,
      customLabel,
      isPrimary,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Address {
  var address: String
  var label: String
  var customLabel: String
  var street: String
  var pobox: String
  var neighborhood: String
  var city: String
  var state: String
  var postalCode: String
  var country: String
  var isoCountry: String
  var subAdminArea: String
  var subLocality: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Address? {
    let address = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let customLabel = pigeonVar_list[2] as! String
    let street = pigeonVar_list[3] as! String
    let pobox = pigeonVar_list[4] as! String
    let neighborhood = pigeonVar_list[5] as! String
    let city = pigeonVar_list[6] as! String
    let state = pigeonVar_list[7] as! String
    let postalCode = pigeonVar_list[8] as! String
    let country = pigeonVar_list[9] as! String
    let isoCountry = pigeonVar_list[10] as! String
    let subAdminArea = pigeonVar_list[11] as! String
    let subLocality = pigeonVar_list[12] as! String

    return Address(
      address: address,
      label: label,
      customLabel: customLabel,
      street: street,
      pobox: pobox,
      neighborhood: neighborhood,
      city: city,
      state: state,
      postalCode: postalCode,
      country: country,
      isoCountry: isoCountry,
      subAdminArea: subAdminArea,
      subLocality: subLocality
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      label,
      customLabel,
      street,
      pobox,
      neighborhood,
      city,
      state,
      postalCode,
      country,
      isoCountry,
      subAdminArea,
      subLocality,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Organization {
  var company: String
  var title: String
  var department: String
  var jobDescription: String
  var symbol: String
  var phoneticName: String
  var officeLocation: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Organization? {
    let company = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let department = pigeonVar_list[2] as! String
    let jobDescription = pigeonVar_list[3] as! String
    let symbol = pigeonVar_list[4] as! String
    let phoneticName = pigeonVar_list[5] as! String
    let officeLocation = pigeonVar_list[6] as! String

    return Organization(
      company: company,
      title: title,
      department: department,
      jobDescription: jobDescription,
      symbol: symbol,
      phoneticName: phoneticName,
      officeLocation: officeLocation
    )
  }
  func toList() -> [Any?] {
    return [
      company,
      title,
      department,
      jobDescription,
      symbol,
      phoneticName,
      officeLocation,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Website {
  var url: String
  var label: String
  var customLabel: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Website? {
    let url = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let customLabel = pigeonVar_list[2] as! String

    return Website(
      url: url,
      label: label,
      customLabel: customLabel
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      label,
      customLabel,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SocialMedia {
  var userName: String
  var label: String
  var customLabel: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SocialMedia? {
    let userName = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let customLabel = pigeonVar_list[2] as! String

    return SocialMedia(
      userName: userName,
      label: label,
      customLabel: customLabel
    )
  }
  func toList() -> [Any?] {
    return [
      userName,
      label,
      customLabel,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Event {
  var year: Int64? = nil
  var month: Int64
  var day: Int64
  var label: String
  var customLabel: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Event? {
    let year: Int64? = nilOrValue(pigeonVar_list[0])
    let month = pigeonVar_list[1] as! Int64
    let day = pigeonVar_list[2] as! Int64
    let label = pigeonVar_list[3] as! String
    let customLabel = pigeonVar_list[4] as! String

    return Event(
      year: year,
      month: month,
      day: day,
      label: label,
      customLabel: customLabel
    )
  }
  func toList() -> [Any?] {
    return [
      year,
      month,
      day,
      label,
      customLabel,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Note {
  var note: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Note? {
    let note = pigeonVar_list[0] as! String

    return Note(
      note: note
    )
  }
  func toList() -> [Any?] {
    return [
      note
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Account {
  var rawId: String
  var name: String
  var type: String
  var mimetypes: [String?]



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Account? {
    let rawId = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let type = pigeonVar_list[2] as! String
    let mimetypes = pigeonVar_list[3] as! [String?]

    return Account(
      rawId: rawId,
      name: name,
      type: type,
      mimetypes: mimetypes
    )
  }
  func toList() -> [Any?] {
    return [
      rawId,
      name,
      type,
      mimetypes,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Group {
  var id: String
  var name: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Group? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String

    return Group(
      id: id,
      name: name
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Contact {
  var id: String
  var displayName: String
  var isStarred: Bool
  var name: Name? = nil
  var thumbnail: FlutterStandardTypedData? = nil
  var photo: FlutterStandardTypedData? = nil
  var phones: [Phone?]
  var emails: [Email?]
  var addresses: [Address?]
  var organizations: [Organization?]
  var websites: [Website?]
  var socialMedias: [SocialMedia?]
  var events: [Event?]
  var notes: [Note?]
  var accounts: [Account?]
  var groups: [Group?]



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Contact? {
    let id = pigeonVar_list[0] as! String
    let displayName = pigeonVar_list[1] as! String
    let isStarred = pigeonVar_list[2] as! Bool
    let name: Name? = nilOrValue(pigeonVar_list[3])
    let thumbnail: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[4])
    let photo: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[5])
    let phones = pigeonVar_list[6] as! [Phone?]
    let emails = pigeonVar_list[7] as! [Email?]
    let addresses = pigeonVar_list[8] as! [Address?]
    let organizations = pigeonVar_list[9] as! [Organization?]
    let websites = pigeonVar_list[10] as! [Website?]
    let socialMedias = pigeonVar_list[11] as! [SocialMedia?]
    let events = pigeonVar_list[12] as! [Event?]
    let notes = pigeonVar_list[13] as! [Note?]
    let accounts = pigeonVar_list[14] as! [Account?]
    let groups = pigeonVar_list[15] as! [Group?]

    return Contact(
      id: id,
      displayName: displayName,
      isStarred: isStarred,
      name: name,
      thumbnail: thumbnail,
      photo: photo,
      phones: phones,
      emails: emails,
      addresses: addresses,
      organizations: organizations,
      websites: websites,
      socialMedias: socialMedias,
      events: events,
      notes: notes,
      accounts: accounts,
      groups: groups
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      displayName,
      isStarred,
      name,
      thumbnail,
      photo,
      phones,
      emails,
      addresses,
      organizations,
      websites,
      socialMedias,
      events,
      notes,
      accounts,
      groups,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ContactsRequest {
  var withProperties: Bool
  var withThumbnail: Bool
  var withPhoto: Bool
  var withGroups: Bool
  var withAccounts: Bool
  var returnUnifiedContacts: Bool
  var includeNotesOnIos13AndAbove: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContactsRequest? {
    let withProperties = pigeonVar_list[0] as! Bool
    let withThumbnail = pigeonVar_list[1] as! Bool
    let withPhoto = pigeonVar_list[2] as! Bool
    let withGroups = pigeonVar_list[3] as! Bool
    let withAccounts = pigeonVar_list[4] as! Bool
    let returnUnifiedContacts = pigeonVar_list[5] as! Bool
    let includeNotesOnIos13AndAbove = pigeonVar_list[6] as! Bool

    return ContactsRequest(
      withProperties: withProperties,
      withThumbnail: withThumbnail,
      withPhoto: withPhoto,
      withGroups: withGroups,
      withAccounts: withAccounts,
      returnUnifiedContacts: returnUnifiedContacts,
      includeNotesOnIos13AndAbove: includeNotesOnIos13AndAbove
    )
  }
  func toList() -> [Any?] {
    return [
      withProperties,
      withThumbnail,
      withPhoto,
      withGroups,
      withAccounts,
      returnUnifiedContacts,
      includeNotesOnIos13AndAbove,
    ]
  }
}

private class ContactsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermisionsApi(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return Name.fromList(self.readValue() as! [Any?])
    case 131:
      return Phone.fromList(self.readValue() as! [Any?])
    case 132:
      return Email.fromList(self.readValue() as! [Any?])
    case 133:
      return Address.fromList(self.readValue() as! [Any?])
    case 134:
      return Organization.fromList(self.readValue() as! [Any?])
    case 135:
      return Website.fromList(self.readValue() as! [Any?])
    case 136:
      return SocialMedia.fromList(self.readValue() as! [Any?])
    case 137:
      return Event.fromList(self.readValue() as! [Any?])
    case 138:
      return Note.fromList(self.readValue() as! [Any?])
    case 139:
      return Account.fromList(self.readValue() as! [Any?])
    case 140:
      return Group.fromList(self.readValue() as! [Any?])
    case 141:
      return Contact.fromList(self.readValue() as! [Any?])
    case 142:
      return ContactsRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ContactsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PermisionsApi {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? Name {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? Phone {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? Email {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? Address {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? Organization {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? Website {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? SocialMedia {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? Event {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? Note {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? Account {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? Group {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? Contact {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? ContactsRequest {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ContactsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ContactsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ContactsPigeonCodecWriter(data: data)
  }
}

class ContactsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ContactsPigeonCodec(readerWriter: ContactsPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ContactsHostApi {
  func getContacts(config: ContactsRequest, completion: @escaping (Result<[Contact], Error>) -> Void)
  func getContactsWithName(name: String, config: ContactsRequest, completion: @escaping (Result<[Contact], Error>) -> Void)
  func getContactsWithEmail(email: String, config: ContactsRequest, completion: @escaping (Result<[Contact], Error>) -> Void)
  func getContactsWithPhone(phone: String, config: ContactsRequest, completion: @escaping (Result<[Contact], Error>) -> Void)
  func getContactsWithIds(ids: [String], config: ContactsRequest, completion: @escaping (Result<[Contact], Error>) -> Void)
  func getContactsInGroup(groupId: String, config: ContactsRequest, completion: @escaping (Result<[Contact], Error>) -> Void)
  func getContactsInContainer(containerId: String, config: ContactsRequest, completion: @escaping (Result<[Contact], Error>) -> Void)
  func checkPermission(completion: @escaping (Result<PermisionsApi, Error>) -> Void)
  func requestPermission(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ContactsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ContactsPigeonCodec.shared }
  /// Sets up an instance of `ContactsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ContactsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getContactsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.getContacts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContactsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ContactsRequest
        api.getContacts(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContactsChannel.setMessageHandler(nil)
    }
    let getContactsWithNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.getContactsWithName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContactsWithNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let configArg = args[1] as! ContactsRequest
        api.getContactsWithName(name: nameArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContactsWithNameChannel.setMessageHandler(nil)
    }
    let getContactsWithEmailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.getContactsWithEmail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContactsWithEmailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let emailArg = args[0] as! String
        let configArg = args[1] as! ContactsRequest
        api.getContactsWithEmail(email: emailArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContactsWithEmailChannel.setMessageHandler(nil)
    }
    let getContactsWithPhoneChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.getContactsWithPhone\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContactsWithPhoneChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let phoneArg = args[0] as! String
        let configArg = args[1] as! ContactsRequest
        api.getContactsWithPhone(phone: phoneArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContactsWithPhoneChannel.setMessageHandler(nil)
    }
    let getContactsWithIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.getContactsWithIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContactsWithIdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idsArg = args[0] as! [String]
        let configArg = args[1] as! ContactsRequest
        api.getContactsWithIds(ids: idsArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContactsWithIdsChannel.setMessageHandler(nil)
    }
    let getContactsInGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.getContactsInGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContactsInGroupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let groupIdArg = args[0] as! String
        let configArg = args[1] as! ContactsRequest
        api.getContactsInGroup(groupId: groupIdArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContactsInGroupChannel.setMessageHandler(nil)
    }
    let getContactsInContainerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.getContactsInContainer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContactsInContainerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let containerIdArg = args[0] as! String
        let configArg = args[1] as! ContactsRequest
        api.getContactsInContainer(containerId: containerIdArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContactsInContainerChannel.setMessageHandler(nil)
    }
    let checkPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.checkPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPermissionChannel.setMessageHandler { _, reply in
        api.checkPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkPermissionChannel.setMessageHandler(nil)
    }
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.dinastyonline.flutter_contacts_plus.ContactsHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        api.requestPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
  }
}
